# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: demoworkspace # Updated namespace
  postfix: 001 # Updated postfix
  location: eastus # Updated location

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # For pipeline reference
  resource_group: default_resourse_group
  aml_workspace: demo_workspace
  application_insights: demoworkspace1997734687
  key_vault: demoworkspace9715646723
  container_registry: a9c528dba4cc4042a824b912e74ef850
  storage_account: demoworkspace0813584800
